---
site_name: Wikisio
site_description: Personal wiki where I share what I learn
site_author: Dionisio Cortés Fernández
site_url: https://github.com/dionisioC/wikisio
nav:
  - Introduction: index.md
  - TODO: TODO.md
  - OS:
      - Arch linux:
          - SSH:
              - os/arch/ssh/config_ssh_key_keyring_arch_i3.md
  - Coding:
      - JavaScript / TypeScript:
          - Express: coding/express/rest_api_with_express.md
      - Tooling:
          - Podman: coding/tooling/podman.md
          - Localstack:
              - DynamoDb: coding/tooling/localstack_DynamoDb.md
plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  custom_dir: theme
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css: [stylesheets/extra.css, stylesheets/links.css]

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dionisioC

repo_name: dionisioC/wikisio
repo_url: https://github.com/dionisioC/wikisio
